### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by Spagliardin** [mariajbrajkovic/FrontEndI#1]
Como va?? Todo lo veo muy bien, lo único a tener en cuenta puede ser lo siguiente:
Cuando tenes dos o mas selectores que comparten el mismo estilo podes juntarlos y así lograr un código mas sintético y limpio. 
Ej:

h1, h2 {
   background-color: darkgray;
   font-size: 20px;
}
--------------------------------------- dejo como si estuvieran comentados los que no irían. -------->
h1 {
    text-align: center;
  /*  background-color: darkgray; */
    margin: 0px;
    color: midnightblue;
 /*   font-size: 20px; */
    line-height: 50px;
}
.batman {
    margin: 20px;
}
header {
    margin: 0;
    text-align: center;
    background-color: lightgrey;
}
h2 {
    color: firebrick;
    margin: 40px 0 0 0;
  /*  background-color: darkgray; */
    width: 70%;
  /*  font-size: 20px; */

**Comment by mariajbrajkovic** [comment]
Buenísimo profe. Ahí ya subí el archivo con las correcciones. Saludos y gracias!
